name: Add version tag

on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml

jobs:
  add-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: butlerlogic/action-autotag@stable
        with:
          root: "./pyproject.toml"
          regex_pattern: "version\\s=\\s\"(?<version>(\\d+(\\.)?){3})\""
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"