name: Pure.py CI

on:
  push:
    branches:
      - 'main'
    paths:
      - "**.py"
      - ".github/**/*.yml"
      - "!pyproject.toml"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**.py"
      - ".github/**/*.yml"
      
jobs:
  test-in-ci:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project manager
        run: >
          curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py \
          | python3 -

      - name: Create env
        run: |
          pdm venv create --name py-${{ matrix.python-version }} ${{ matrix.python-version }}

      - name: Activate env
        run: |
          eval $(pdm venv activate py-${{ matrix.python-version }}) 

      - name: Install project dependencies
        run: |
          pdm install --verbose

      - name: Run Tests
        run: |
          pdm run make tests-unit-only

  bump-version: # Bump when on master
    needs: [test-in-ci]
    if: contains(github.ref, 'master')
    uses: ./.github/workflows/bump-version.yml
    secrets: inherit
