name: Add version tag

on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml

jobs:
  add-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install project manager
        run: >
          curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py \
          | python3 -

      - name: Install project dependencies
        run: |
          pdm install

      - name: Publish to pipy
        env:
          PURE_PYPI_TOKEN: ${{ secrets.PURE_PYPI_TOKEN }}
        run: |
          make publish-to-test-pipy