name: Publish package

on:
  workflow_call:

jobs:
  publish-to-pipy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install PDM
        uses: pdm-project/setup-pdm@main

      - name: Build Package
        run: pdm build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PURE_PYPI_TOKEN }}
          repository_url: https://pypi.org/legacy/
          # password: ${{ secrets.PURE_TESTPYPI_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/